### PR TITLE
Bugfix/update dom on modal close

### PR DESCRIPTION
**Pull request by skuethe**
Hey there,

small fix from my side: use lockstrings and update the Dom after we hide the Modal.
This came up when using MMM-Modal with [MMM-pages](https://github.com/edward-shen/MMM-pages):

MMM-pages is `pausing` modules which are not configured on the current page and resumes them when they are.
This caused a problem when I used MMM-Modal at least once after a fresh start, because the "old" Modal is still an active Dom element and will be shown again if the module is resumed via MMM-pages. So steps to reproduce:

1. Restart MM² with MMM-pages and MMM-Modal active. MMM-Modal can be put in the `fixed` array of MMM-pages to show on every page
2. Show any Modal with your preferred / implemented way
3. Close that Modal
4. swap pages with MMM-pages
5. MMM-Modal will get "resumed" by MMM-pages and re-show the before hidden Modal content

This is happening because on `closeModal` function we are hiding itself (so "pausing" it) and MMM-pages is using the same mechanic to resume it.
Using [lockStrings](https://docs.magicmirror.builders/development/core-module-file.html#visibility-locking) we can keep control over when to show and hide Modals to this module.
I also added the Dom update command when hiding a module just to be more "clean" (this was my first fix before also using lockStrings).

When MMM-pages is now trying to resume MMM-Modal, we see the following console log:
`Will not show MMM-Modal. LockStrings active: module_13_MMM-Modal`

Let me know if you need more information :)
This **should not** break any current implementations. I tested on my current setup with two modules showing different content via MMM-modal.

### CODE REVIEW

**Review by fewieden — COMMENTED** [review]
As MMM-Modal is more acting as a global module, I think opening a Modal e.g. by voice should make use of the force option to show a module in order to always show a modal even if another module was hiding it. Modals are usually only shown upon user interaction. What do you think?

https://github.com/MichMich/MagicMirror/blob/ec08cb32aa880f09d772c8cd869e7e0d2faf194f/js/main.js#L296-L307

**Comment by skuethe** [comment]
Yeah I thought about that. And I totally agree that MMM-Modal should have the only "saying" in when to actually show the modal and when not.
In theory, if every module is using lockstrings "the right way" there should not be a situation where you would actually need to force show it, right?
But there will always be some edge case or maybe a flawed integration where this will then break usage of this module.

Maybe we could introduce a new config option to force it if necessary / wanted?
Then in most cases users would not have to fiddle around with this setting at all and only users which are running into problems would have a closer look at it?
Something Like `forceResumeOverwrite` or similar?!

**Comment by skuethe** [comment]
So, do you have any thoughts on this? :) How should we proceed?

**Comment by fewieden** [comment]
@skuethe I didn't have much time recently. I will try to create your setup and have a look what we can/should do here.

Did I understand correctly, that I need the following?
- MMM-pages (MMM-Modal in fixed array)
- MMM-Modal
- Another module that triggers a modal

If you want you can also post your config without credentials and api keys

**Comment by skuethe** [comment]
Thanks for coming back to me. Here is my current setup (cleaned up with only the necessary modules in-place.
`MMM-Spotify` and `MMM-WiFiPassword` are the modules triggering `MMM-Modal`, as Spotify needs an active account, probably easiest to test only with MMM-WiFiPassword (by "swiping up" with one finger - see `MMM-Touch` module) or / and your module of choice.

```js
    {
      module: "MMM-pages",
      position: "fullscreen_below",
      config: {
        modules: [
          [ "weather" ],
          [ "MMM-Spotify" ],
        ], 
        fixed: ["clock", "MMM-page-indicator", "MMM-Touch", "MMM-Modal" ],
      }
    },
    {
      module: "clock",
      position: "top_left",
      config: {
        clockBold: false,
        showWeek: true
      }
    },
    {
      module: "weather",
      header: "Wetter",
      position: "bottom_left",
      config: {
        type: "current",
        onlyTemp: false,
        showWindDirection: false,
        showFeelsLike: true,
        showSun: true,
        weatherProvider: "openweathermap",
        apiKey: "[APIKEY]",
        locationID: "[LOCATIONID]"
      }
    },
    {
      module: "MMM-WiFiPassword",
      position: "bottom_right",
      config: {
        qrSize: 300,
        network: "[WIFI]",
        password: "[WIFIPASS]",
        showNetwork: false,
        showPassword: false,
        showAuthType: false, 
        startHidden: true, 
      }
    },
    { 
      module: "MMM-Spotify",
      position: "top_center",
      config: {
        debug: false,
        style: "default",
        moduleWidth: 450,
        control: "default",
        showAccountButton: true,
        showDeviceButton: true,
        useExternalModal: true,
        onStart: null,
        idleInterval: 10000,
        allowDevices: [
        ],
        notificationsOnSuspend: [
          {
            notification: "SPOTIFY_SUSPENDED",
          },
        ],
        notificationsOnResume: [
          {
            notification: "SPOTIFY_RESUMED",
          },
        ],
      }
    },
    {
      module: "MMM-Modal",
      position: "fullscreen_below",
      config: {
        timer: false,
        touch: false,
      }
    },
    {
      // Have this at the bottom, or else it will "push" down other modules comming after it, even tho it is "hidden"
      module: "MMM-Touch",
      position: "top_right",
      config: {
        useDisplay: false,
        threshold: {
          moment_ms: 1000 * 0.5,
          double_ms: 1000 * 0.75,
          press_ms: 1000 * 3,
          move_px: 50,
          pinch_px: 50,
          rotate_dg: 20,
          idle_ms: 300000,
        },
        defaultMode: "normalOperation",
        gestureCommands: {
          // normalOperations - show all of interest
          "normalOperation": {
            // Show Wifi QR code
            "SWIPE_UP_1": (commander, gesture) => {
              let module = commander.getModule("MMM-WiFiPassword");
              module.modalActive = !module.modalActive;
              if (module.modalActive) {
                commander.sendNotification("WIFIPASSWORD_MODAL");
              } else {
                commander.sendNotification("CLOSE_MODAL");
              }
            },
            // work with MMM-pages - next page
            "SWIPE_LEFT_1": (commander, gesture) => {
              commander.sendNotification("PAGE_INCREMENT")
            },
            // work with MMM-pages - previous page
            "SWIPE_RIGHT_1": (commander, gesture) => {
              commander.sendNotification("PAGE_DECREMENT")
            },
          },
        }
      }
    },
    {
      module: "MMM-page-indicator",
      position: "bottom_bar"
    }
```

**Comment by fewieden** [comment]
@skuethe I ran into some issues testing it, therefore I made some adjustments.

I set a required minimum version, because the bug fix of https://github.com/MichMich/MagicMirror/pull/2385 is necessary.

**Comment by skuethe** [comment]
Okay, I did not run into any noticeable problems the last two months while already running this. But good thing you noticed :)
I will update to 2.14.0 in the next days to test the changes.

**Comment by fewieden** [comment]
@skuethe in particular I called hide with a random lock string and then swiped up again. It was blurring all modules, but couldn't show MMM-Modal.

Let me know once you tested it with 2.14

**Comment by skuethe** [comment]
A first quick test is showing that `MMM-Modal` callback functionality I use within `MMM-Spotify` is now broken.
If I revert the changes from your last commit, everything works fine with the new MM version 2.14.0. Need to look deeper into it with debugging enabled.

**Comment by fewieden** [comment]
@skuethe I finally found the issue when you couldn't open a modal if another one was currently displayed. Opening of the new modal and closing of the old one conflicted.

Now I only notify the other module rather than completely closing the modal if there is currently a modal.

Does this also solve the issue you had with the spotify module?

**Comment by skuethe** [comment]
Sorry for the delay, I am quite busy currently :(
So I just tested with your latest commit, but the callback seems to still be broken / not working.
I haven't come around into debugging the issue, but I hope I can do that later in the evening or tomorrow.

**Comment by fewieden** [comment]
@skuethe I don't have a spotify premium account. What exactly are you doing in the module to run into this issue? Maybe I can mock the state and help to debug.

**Comment by skuethe** [comment]
There are two implementations in MMM-Spotify which are more or less the same but with different data being displayed:

1. I use it to switch between different accounts:
https://github.com/skuethe/MMM-Spotify/blob/master/MMM-Spotify.js#L874-L893
2. I use it to switch between different playback devices
https://github.com/skuethe/MMM-Spotify/blob/master/MMM-Spotify.js#L903-L921

So what happens: You click f.e. the "account switch" button, the modal opens up and gives you a list of available accounts. You press any entry, the modal closes and reports the selected account ID back to MMM-Spotify.
The same implementation with the "device switch" button. It lists all available playback devices and after you click one, it gives feedback to MMM-Spotify, closes the modal and switches to the selected playbackdevice.

I really try to find some time in the next few days, so we can get this PR worked out :) thank you for your patience

**Comment by fewieden** [comment]
@skuethe I mocked now the whole MMM-Spotify module. The problem is that the line here https://github.com/MichMich/MagicMirror/blob/develop/js/main.js#L219 adds the DOM of the modal asynchronously, which happens after the callback has been triggered already.

Therefore your `const modalList = document.getElementById("SPOTIFY_MODAL_LIST");` is always null.

So we have two problems:
- With the introduced `lockStrings` and the old commands we could run into issues that the mirror gets blurred without displaying a modal.
- We use the show callback to fix the issue above but then the render callback gets triggered too fast.

I implemented a fix for it, but I don't really like it.
- `updateDom` is async but doesn't provide a promise or callback, therefore I needed to set a timeout.
- show callback doesn't get triggered if there are active `lockStrings` due to the area I don't think we can introduce promises/callbacks with error prop, as this would probably break a lot of modules. Just a bad design of the core from the start.

**Comment by fewieden** [comment]
@skuethe I created a PR to fix the callback not being sent when lockStrings are active. After this is merged we should update the modal options callback to follow the same design principle that I described in the PR `callback(error, data)`. Also, when we retrieve the error here we should no longer trigger the rest in the callback.

The `updateDom` timeout needs to remain for now. This would take a lot of effort to change and is more likely to break modules.

**Comment by fewieden** [comment]
I looked through all the modules that implemented MMM-Modal. We would need to update [MMM-Fuel](https://github.com/fewieden/MMM-Fuel) and [MMM-Spotify](https://github.com/skuethe/MMM-Spotify), the others do not use the oiptions callback, after we change the function signature.

**Comment by skuethe** [comment]
Thank you for your hard work and support @fewieden !

**Comment by fewieden** [comment]
@skuethe I made changes to the call signature of the callback and adjusted the callbacks of `module.show` in https://github.com/MichMich/MagicMirror/pull/2439. After this gets merged you need to adjust

https://github.com/skuethe/MMM-Spotify/blob/master/MMM-Spotify.js#L892 and https://github.com/skuethe/MMM-Spotify/blob/master/MMM-Spotify.js#L920

**Comment by fewieden** [comment]
@skuethe I released the new version and the required change was also merged on the core project. You can now make the change in the spotify project.

**Comment by skuethe** [comment]
Thank you again for your support. I am currently still waiting to implement this, as MagicMirror² release `2.15.0` is [still missing](https://github.com/MichMich/MagicMirror/releases/latest).
I really hoped for the release on 1st of March, but there seems to be a delay.

**Comment by fewieden** [comment]
@skuethe MagicMirror² releases quarterly so far, so the next planned release is the 1st of April.

**Comment by skuethe** [comment]
Argh, you are totally right. Somehow I thought it was 2 month cycle :|

**Pull request merged**
